name: nut_products_e_shop
description: Nut products e-shop.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The scheme for versioning is:
# major * 100 000 000 + minor * 1 000 000 + patch * 10 000 + build
# 0.0.1+1 -> 000_010_001 => 000010001
# 1.2.3+4 -> 102_030_004 => 102030004
# 2.8.4   -> 208_040_000 => 208040000
version: 0.0.1+000010001

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ^3.19.3

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_layout_grid: 2.0.5
  flutter_rating_bar: 4.0.1
  flutter_riverpod: 2.5.1
  go_router: 13.2.1
  intl: 0.19.0
  path_provider: 2.1.2
  riverpod_annotation: 2.3.5
  riverpod_generator: 2.4.0
  rxdart: 0.27.7
  sembast: 3.6.0
  sembast_web: 2.3.0

dev_dependencies:
  build_runner: 2.4.8
  custom_lint: 0.6.4
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 1.0.3
  riverpod_lint: 2.3.10

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
  # Used for Golden Image tests
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    # Add all product images
    - assets/products/
