name: nut_products_e_shop
description: Nut products e-shop.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  collection: 1.18.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_layout_grid: 2.0.5
  flutter_rating_bar: 4.0.1
  flutter_riverpod: 2.4.9
  go_router: 13.0.1
  intl: 0.19.0
  rxdart: 0.27.7

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  mocktail: 1.0.2
  riverpod_generator: 2.3.9
  riverpod_lint: 2.3.7

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all product images
    - assets/products/
